# Generated by Django 4.0.4 on 2022-05-30 12:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediumish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='about',
        ),
        migrations.CreateModel(
            name='Authorprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Authorprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
