# Generated by Django 4.0.4 on 2022-06-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumish', '0021_remove_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
