# Generated by Django 4.0.4 on 2022-06-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumish', '0022_remove_user_date_of_birth_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
