# Generated by Django 4.0.4 on 2022-06-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediumish', '0029_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
