# Generated by Django 4.0.4 on 2022-06-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediumish', '0030_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
